### ISSUE TITLE
calendar events handler

### ISSUE THREAD

**Issue by ivansglazunov** [deepcase/boilerplate#13]

**Comment by valentineus** [comment]
# Краткий очерк имеющихся протоколов

## Популярные решения

* [CalDAV](https://en.wikipedia.org/wiki/CalDAV). Расширение WebDAV протокола. Поддерживается компаниями Google, Yandex, Apple.

## Проприетарные решения

* [iCalendar](https://en.wikipedia.org/wiki/ICalendar). Поддерживается и развивается компанией Apple.

* [Exchange ActiveSync (EAS)](https://en.wikipedia.org/wiki/Exchange_ActiveSync). Протокол синхронизации данных от компании Microsoft. Используется в мобильных устройствах. Спроектирован, как легковесный протокол. Ограничен в возможностях и передаваемых данных.

* [Exchange Web Services (EWS)](https://en.wikipedia.org/wiki/Microsoft_Exchange_Server) Протокол синхронизации данных от компании Microsoft. Используется в стационарных устройствах.
