### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by ivansglazunov** [deepcase/boilerplate#19]

**Comment by ivansglazunov** [comment]
What type of license would you prefer?

**Comment by valentineus** [comment]
I prefer the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license. This license is free as [MIT](https://en.wikipedia.org/wiki/MIT_License) license. But source code protects by an intellectual property right.

* https://zgp.org/~dmarti/qanda/what-are-the-differences-between-open-source-licenses/

**Comment by ivansglazunov** [comment]
Because given the only one answer, and the fact that I also prefer MIT, the temporary choice is MIT.

**Comment by ivansglazunov** [comment]
Sorry, I didn’t eat it carefully, now I’m shitting apache and mit

**Comment by ivansglazunov** [comment]
Apache requires to mention the license in every file. Meath does not require. I don't see any advantages. What exactly is better to choose Apache 2 against MIT?

**Comment by ivansglazunov** [comment]
May be WTFPL?

**Comment by ivansglazunov** [comment]
This issue closed. This opened: https://github.com/deepcase/deepcase/issues/23
