### ISSUE TITLE
auth

### ISSUE THREAD

**Issue by ivansglazunov** [deepcase/boilerplate#5]
~~- [ ] jws/token auth~~
~~- [ ] move from private deepcase repo realized auth with secred code (sms/email... any)~~
~~- [ ] move from private deepcase repo realized password auth~~
- [x] check compatibility with passportjs package with many auth methods

**Comment by Konard** [comment]
Can you provide a descriptive title or description?

**Comment by ivansglazunov** [comment]
done

**Comment by ivansglazunov** [comment]
+ Added passport is draft realisation.
- Not modular passport config
- Not yet client relogin without
