### ISSUE TITLE
hasura support

### ISSUE THREAD

**Issue by ivansglazunov** [deepcase/boilerplate#7]
- [x] integrated transactioned migrations for postgres and hasura metadata
- [x] easy local starter
- [x] apollo/relay connector
- [x] event-handler boilerplate in nextjs api
- [x] remote-schema boilerplate in nextjs api

**Comment by Konard** [comment]
Can you provide a descriptive title or description?

**Comment by ivansglazunov** [comment]
> Can you provide a descriptive title or description?

done
